//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanHafner.Smartbar.ProcessApplication.Plugins.SystemTools.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JanHafner.Smartbar.ProcessApplication.Plugins.SystemTools.Localization.DisplayTex" +
                            "ts", typeof(DisplayTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Management.
        /// </summary>
        internal static string Compmgmt {
            get {
                return ResourceManager.GetString("Compmgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defragmentation.
        /// </summary>
        internal static string Defrag {
            get {
                return ResourceManager.GetString("Defrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Management.
        /// </summary>
        internal static string Devmgmt {
            get {
                return ResourceManager.GetString("Devmgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Management.
        /// </summary>
        internal static string Diskmgmt {
            get {
                return ResourceManager.GetString("Diskmgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Viewer.
        /// </summary>
        internal static string Eventvwr {
            get {
                return ResourceManager.GetString("Eventvwr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Folders.
        /// </summary>
        internal static string Fsmgmt {
            get {
                return ResourceManager.GetString("Fsmgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows &quot;God Mode&quot;.
        /// </summary>
        internal static string GodMode {
            get {
                return ResourceManager.GetString("GodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Policies.
        /// </summary>
        internal static string Gpedit {
            get {
                return ResourceManager.GetString("Gpedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration.
        /// </summary>
        internal static string Msconfig {
            get {
                return ResourceManager.GetString("Msconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs and Functions.
        /// </summary>
        internal static string ProgramsAndFunctions {
            get {
                return ResourceManager.GetString("ProgramsAndFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Policies.
        /// </summary>
        internal static string Secpol {
            get {
                return ResourceManager.GetString("Secpol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Users and Groups.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall.
        /// </summary>
        internal static string Wf {
            get {
                return ResourceManager.GetString("Wf", resourceCulture);
            }
        }
    }
}
