//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanHafner.Smartbar.ProcessApplication.EditProcessApplication.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditProcessApplication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditProcessApplication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JanHafner.Smartbar.ProcessApplication.EditProcessApplication.Localization.EditPro" +
                            "cessApplication", typeof(EditProcessApplication).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure advanced information.
        /// </summary>
        internal static string EditProcessApplicationAdvancedGroupBoxHeader {
            get {
                return ResourceManager.GetString("EditProcessApplicationAdvancedGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string EditProcessApplicationAdvancedTabHeader {
            get {
                return ResourceManager.GetString("EditProcessApplicationAdvancedTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affinity mask:.
        /// </summary>
        internal static string EditProcessApplicationAffinityMaskLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationAffinityMaskLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} logical processors selected.
        /// </summary>
        internal static string EditProcessApplicationAffinityMaskSelectedBitCountLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationAffinityMaskSelectedBitCountLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set affinity mask for the application.
        /// </summary>
        internal static string EditProcessApplicationAffinityMaskTooltip {
            get {
                return ResourceManager.GetString("EditProcessApplicationAffinityMaskTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments:.
        /// </summary>
        internal static string EditProcessApplicationArgumentsLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationArgumentsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure common information.
        /// </summary>
        internal static string EditProcessApplicationCommonGroupBoxHeader {
            get {
                return ResourceManager.GetString("EditProcessApplicationCommonGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string EditProcessApplicationCommonTabHeader {
            get {
                return ResourceManager.GetString("EditProcessApplicationCommonTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to determine application name automatically.
        /// </summary>
        internal static string EditProcessApplicationDetermineApplicationNameTooltip {
            get {
                return ResourceManager.GetString("EditProcessApplicationDetermineApplicationNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the configuration associated with the application..
        /// </summary>
        internal static string EditProcessApplicationDialogDescriptionText {
            get {
                return ResourceManager.GetString("EditProcessApplicationDialogDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure application.
        /// </summary>
        internal static string EditProcessApplicationDialogTitle {
            get {
                return ResourceManager.GetString("EditProcessApplicationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute:.
        /// </summary>
        internal static string EditProcessApplicationExecuteLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationExecuteLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down at least shift, alt and/or control and the key to set the hot key.
        ///If you want to set a hot key and the box keeps empty, it is possible that the hot key is already associated and was activated!.
        /// </summary>
        internal static string EditProcessApplicationHotKeyKeepsEmptyInfoText {
            get {
                return ResourceManager.GetString("EditProcessApplicationHotKeyKeepsEmptyInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey:.
        /// </summary>
        internal static string EditProcessApplicationHotKeyLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationHotKeyLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string EditProcessApplicationNameLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationNameLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps lock is on..
        /// </summary>
        internal static string EditProcessApplicationPasswordCapsLockIsOn {
            get {
                return ResourceManager.GetString("EditProcessApplicationPasswordCapsLockIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string EditProcessApplicationPasswordLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationPasswordLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process priority:.
        /// </summary>
        internal static string EditProcessApplicationProcessPriorityClassLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationProcessPriorityClassLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window style:.
        /// </summary>
        internal static string EditProcessApplicationProcessWindowStyleLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationProcessWindowStyleLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as....
        /// </summary>
        internal static string EditProcessApplicationRunAsGroupBoxHeader {
            get {
                return ResourceManager.GetString("EditProcessApplicationRunAsGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory to open.
        /// </summary>
        internal static string EditProcessApplicationSelectDirectoryDialogTitle {
            get {
                return ResourceManager.GetString("EditProcessApplicationSelectDirectoryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory to open.
        /// </summary>
        internal static string EditProcessApplicationSelectDirectoryTooltip {
            get {
                return ResourceManager.GetString("EditProcessApplicationSelectDirectoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to start.
        /// </summary>
        internal static string EditProcessApplicationSelectFilePathDialogTitle {
            get {
                return ResourceManager.GetString("EditProcessApplicationSelectFilePathDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to start.
        /// </summary>
        internal static string EditProcessApplicationSelectFilePathTooltip {
            get {
                return ResourceManager.GetString("EditProcessApplicationSelectFilePathTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch small image to fit button size.
        /// </summary>
        internal static string EditProcessApplicationStretchSmallImageLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationStretchSmallImageLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string EditProcessApplicationUsernameLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationUsernameLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a working directory for the application.
        /// </summary>
        internal static string EditProcessApplicationWorkingDirectoryDialogTitle {
            get {
                return ResourceManager.GetString("EditProcessApplicationWorkingDirectoryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory:.
        /// </summary>
        internal static string EditProcessApplicationWorkingDirectoryLabelContent {
            get {
                return ResourceManager.GetString("EditProcessApplicationWorkingDirectoryLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a working directory for the application.
        /// </summary>
        internal static string EditProcessApplicationWorkingDirectoryTooltip {
            get {
                return ResourceManager.GetString("EditProcessApplicationWorkingDirectoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above normal.
        /// </summary>
        internal static string PriorityClassAboveNormal {
            get {
                return ResourceManager.GetString("PriorityClassAboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below normal.
        /// </summary>
        internal static string PriorityClassBelowNormal {
            get {
                return ResourceManager.GetString("PriorityClassBelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string PriorityClassHigh {
            get {
                return ResourceManager.GetString("PriorityClassHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string PriorityClassIdle {
            get {
                return ResourceManager.GetString("PriorityClassIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string PriorityClassNormal {
            get {
                return ResourceManager.GetString("PriorityClassNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime.
        /// </summary>
        internal static string PriorityClassRealtime {
            get {
                return ResourceManager.GetString("PriorityClassRealtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string WindowStyleHidden {
            get {
                return ResourceManager.GetString("WindowStyleHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximized.
        /// </summary>
        internal static string WindowStyleMaximized {
            get {
                return ResourceManager.GetString("WindowStyleMaximized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimized.
        /// </summary>
        internal static string WindowStyleMinimized {
            get {
                return ResourceManager.GetString("WindowStyleMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string WindowStyleNormal {
            get {
                return ResourceManager.GetString("WindowStyleNormal", resourceCulture);
            }
        }
    }
}
