//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanHafner.Smartbar.Views.MainWindow.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JanHafner.Smartbar.Views.MainWindow.Localization.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} updates for plugins available :-). Click here to open plugin manager..
        /// </summary>
        internal static string BallonNotificationPluginUpdatesAvailableText {
            get {
                return ResourceManager.GetString("BallonNotificationPluginUpdatesAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates!.
        /// </summary>
        internal static string BallonNotificationPluginUpdatesAvailableTitle {
            get {
                return ResourceManager.GetString("BallonNotificationPluginUpdatesAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update to version {0} available :-) Click here to update..
        /// </summary>
        internal static string BallonNotificationSmartbarUpdateAvailableText {
            get {
                return ResourceManager.GetString("BallonNotificationSmartbarUpdateAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update!.
        /// </summary>
        internal static string BallonNotificationSmartbarUpdateAvailableTitle {
            get {
                return ResourceManager.GetString("BallonNotificationSmartbarUpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape will discard the name, enter or click beside will accept the name..
        /// </summary>
        internal static string GroupNameTooltipWhileEditing {
            get {
                return ResourceManager.GetString("GroupNameTooltipWhileEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear group.
        /// </summary>
        internal static string MainWindowClearGroupHeader {
            get {
                return ResourceManager.GetString("MainWindowClearGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MainWindowDeleteGroupHeader {
            get {
                return ResourceManager.GetString("MainWindowDeleteGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string MainWindowRenameGroupHeader {
            get {
                return ResourceManager.GetString("MainWindowRenameGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift left.
        /// </summary>
        internal static string MainWindowShiftGroupLeftHeader {
            get {
                return ResourceManager.GetString("MainWindowShiftGroupLeftHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift right.
        /// </summary>
        internal static string MainWindowShiftGroupRightHeader {
            get {
                return ResourceManager.GetString("MainWindowShiftGroupRightHeader", resourceCulture);
            }
        }
    }
}
