//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanHafner.Smartbar.Views.PluginManager.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PluginManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JanHafner.Smartbar.Views.PluginManager.Localization.PluginManager", typeof(PluginManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string ColumnHeaderAuthor {
            get {
                return ResourceManager.GetString("ColumnHeaderAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColumnHeaderDescription {
            get {
                return ResourceManager.GetString("ColumnHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string ColumnHeaderVersion {
            get {
                return ResourceManager.GetString("ColumnHeaderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New plugins were successfully installed or uninstalled!
        ///Restart Smartbar for the change to take effect..
        /// </summary>
        internal static string InstalledPluginsChangedText {
            get {
                return ResourceManager.GetString("InstalledPluginsChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation took too long and was stopped! Not all plugins are displayed..
        /// </summary>
        internal static string LoadAbortedDialogMessage {
            get {
                return ResourceManager.GetString("LoadAbortedDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no packages available for download :-(.
        /// </summary>
        internal static string NoOnlinePackagesAvailableText {
            get {
                return ResourceManager.GetString("NoOnlinePackagesAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The online plugin package source is unavailable!
        ///Only locally installed plugin packages are shown and can be uninstalled..
        /// </summary>
        internal static string OnlinePackageSourceUnavailableText {
            get {
                return ResourceManager.GetString("OnlinePackageSourceUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Explorer.
        /// </summary>
        internal static string OpenModuleExplorerButtonText {
            get {
                return ResourceManager.GetString("OpenModuleExplorerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management, installation and uninstallation of all installed plugins..
        /// </summary>
        internal static string PluginManagerDialogDescriptionText {
            get {
                return ResourceManager.GetString("PluginManagerDialogDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin management.
        /// </summary>
        internal static string PluginManagerDialogTitle {
            get {
                return ResourceManager.GetString("PluginManagerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list.
        /// </summary>
        internal static string RefreshButtonContent {
            get {
                return ResourceManager.GetString("RefreshButtonContent", resourceCulture);
            }
        }
    }
}
