//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanHafner.Smartbar.Common.UserInterface.SelectNativeResource.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SelectNativeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectNativeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JanHafner.Smartbar.Common.UserInterface.SelectNativeResource.Localization.SelectN" +
                            "ativeResource", typeof(SelectNativeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled! Not all icons are displayed..
        /// </summary>
        public static string ExtractionAbortedDialogMessage {
            get {
                return ResourceManager.GetString("ExtractionAbortedDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with resources (.exe; .dll; .ico).
        /// </summary>
        public static string FilesWithResourcesFilterText {
            get {
                return ResourceManager.GetString("FilesWithResourcesFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons could not be extracted, please choose another file..
        /// </summary>
        public static string IconsCouldNotBeExtractDialogMessage {
            get {
                return ResourceManager.GetString("IconsCouldNotBeExtractDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no icons present, please choose another file..
        /// </summary>
        public static string NoIconsFoundInSelectedFileDialogMessage {
            get {
                return ResourceManager.GetString("NoIconsFoundInSelectedFileDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select library....
        /// </summary>
        public static string SelectFromWellKnownIconLibraryButtonText {
            get {
                return ResourceManager.GetString("SelectFromWellKnownIconLibraryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file you wish to extract icons from..
        /// </summary>
        public static string SelectNativeResourceDialogDescriptionText {
            get {
                return ResourceManager.GetString("SelectNativeResourceDialogDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectNativeResourceDialogSelectButton {
            get {
                return ResourceManager.GetString("SelectNativeResourceDialogSelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select resource.
        /// </summary>
        public static string SelectNativeResourceDialogTitle {
            get {
                return ResourceManager.GetString("SelectNativeResourceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string SelectNativeResourceFileLabelContent {
            get {
                return ResourceManager.GetString("SelectNativeResourceFileLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0}.
        /// </summary>
        public static string SelectNativeResourceResourceIdLabelContent {
            get {
                return ResourceManager.GetString("SelectNativeResourceResourceIdLabelContent", resourceCulture);
            }
        }
    }
}
