//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanHafner.Smartbar.Common.UserInterface.SelectNativeResource.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WellKnownIconContainers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WellKnownIconContainers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JanHafner.Smartbar.Common.UserInterface.SelectNativeResource.Localization.WellKno" +
                            "wnIconContainers", typeof(WellKnownIconContainers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string Accessibilitycpl {
            get {
                return ResourceManager.GetString("Accessibilitycpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware and Devices 1.
        /// </summary>
        internal static string Ddores {
            get {
                return ResourceManager.GetString("Ddores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Management.
        /// </summary>
        internal static string Dmdskres {
            get {
                return ResourceManager.GetString("Dmdskres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network 5.
        /// </summary>
        internal static string Dsuiext {
            get {
                return ResourceManager.GetString("Dsuiext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string Gameux {
            get {
                return ResourceManager.GetString("Gameux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer.
        /// </summary>
        internal static string Ieframe {
            get {
                return ResourceManager.GetString("Ieframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Imageres {
            get {
                return ResourceManager.GetString("Imageres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media 1.
        /// </summary>
        internal static string Mmres {
            get {
                return ResourceManager.GetString("Mmres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop.
        /// </summary>
        internal static string Mstscax {
            get {
                return ResourceManager.GetString("Mstscax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network 1.
        /// </summary>
        internal static string Netcenter {
            get {
                return ResourceManager.GetString("Netcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network 2.
        /// </summary>
        internal static string Netshell {
            get {
                return ResourceManager.GetString("Netshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network 3.
        /// </summary>
        internal static string Networkexplorer {
            get {
                return ResourceManager.GetString("Networkexplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network 4.
        /// </summary>
        internal static string Pnidui {
            get {
                return ResourceManager.GetString("Pnidui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        internal static string Sensorscpl {
            get {
                return ResourceManager.GetString("Sensorscpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware and Devices 2.
        /// </summary>
        internal static string Setupapi {
            get {
                return ResourceManager.GetString("Setupapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell.
        /// </summary>
        internal static string Shell32 {
            get {
                return ResourceManager.GetString("Shell32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media 2.
        /// </summary>
        internal static string Wmploc {
            get {
                return ResourceManager.GetString("Wmploc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable and Battery.
        /// </summary>
        internal static string Wpdshext {
            get {
                return ResourceManager.GetString("Wpdshext", resourceCulture);
            }
        }
    }
}
