//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanHafner.Smartbar.Common.UserInterface.SelectIconPackResource.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SelectIconPackResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectIconPackResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JanHafner.Smartbar.Common.UserInterface.SelectIconPackResource.Localization.Selec" +
                            "tIconPackResource", typeof(SelectIconPackResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entypo.
        /// </summary>
        public static string IconPackEntypo {
            get {
                return ResourceManager.GetString("IconPackEntypo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Awesome.
        /// </summary>
        public static string IconPackFontAwesome {
            get {
                return ResourceManager.GetString("IconPackFontAwesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string IconPackMaterial {
            get {
                return ResourceManager.GetString("IconPackMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern.
        /// </summary>
        public static string IconPackModern {
            get {
                return ResourceManager.GetString("IconPackModern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octicons.
        /// </summary>
        public static string IconPackOcticons {
            get {
                return ResourceManager.GetString("IconPackOcticons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled! Not all icons are displayed..
        /// </summary>
        public static string LoadAbortedDialogMessage {
            get {
                return ResourceManager.GetString("LoadAbortedDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string SelectIconPackResourceColorLabel {
            get {
                return ResourceManager.GetString("SelectIconPackResourceColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in icons you can use to give your application a custom look..
        /// </summary>
        public static string SelectIconPackResourceDialogDescriptionText {
            get {
                return ResourceManager.GetString("SelectIconPackResourceDialogDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectIconPackResourceDialogSelectButton {
            get {
                return ResourceManager.GetString("SelectIconPackResourceDialogSelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select built-in icon.
        /// </summary>
        public static string SelectIconPackResourceDialogTitle {
            get {
                return ResourceManager.GetString("SelectIconPackResourceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library:.
        /// </summary>
        public static string SelectIconPackResourceIconPackLabel {
            get {
                return ResourceManager.GetString("SelectIconPackResourceIconPackLabel", resourceCulture);
            }
        }
    }
}
