//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanHafner.Smartbar.Views.EditSmartbarSettings.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditSmartbarSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditSmartbarSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JanHafner.Smartbar.Views.EditSmartbarSettings.Localization.EditSmartbarSettings", typeof(EditSmartbarSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new size is smaller and applications would become invisible!
        ///These applications will be deleted..
        /// </summary>
        internal static string ApplicationsWillBeDeletedDueToSmallerSizeLabelContent {
            get {
                return ResourceManager.GetString("ApplicationsWillBeDeletedDueToSmallerSizeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some plugins are configurable and provide additional possibilities to change their behavior..
        /// </summary>
        internal static string EditSmartbarSettingConfigurePluginsLabelContent {
            get {
                return ResourceManager.GetString("EditSmartbarSettingConfigurePluginsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color scheme:.
        /// </summary>
        internal static string EditSmartbarSettingsAccentColorSchemeLabelContent {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsAccentColorSchemeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearence.
        /// </summary>
        internal static string EditSmartbarSettingsAppearenceTabItemHeader {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsAppearenceTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto select created group.
        /// </summary>
        internal static string EditSmartbarSettingsAutoSelectCreatedGroup {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsAutoSelectCreatedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string EditSmartbarSettingsBehaviorTabItemHeader {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsBehaviorTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns:.
        /// </summary>
        internal static string EditSmartbarSettingsColumnsLabelContent {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsColumnsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can delete group with middle mouse button.
        /// </summary>
        internal static string EditSmartbarSettingsDeleteGroupWithMiddleMouseButton {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsDeleteGroupWithMiddleMouseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion of groups and applications.
        /// </summary>
        internal static string EditSmartbarSettingsDeleteWithConfirmation {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsDeleteWithConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the appearence and behavior of Smartbar and installed plugins..
        /// </summary>
        internal static string EditSmartbarSettingsDialogDescriptionText {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsDialogDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string EditSmartbarSettingsDialogTitle {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct edit of group header via double click.
        /// </summary>
        internal static string EditSmartbarSettingsDirectEditOfGroupHeader {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsDirectEditOfGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content size:.
        /// </summary>
        internal static string EditSmartbarSettingsGridCellContentSizeLabelContent {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsGridCellContentSizeLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content spacing:.
        /// </summary>
        internal static string EditSmartbarSettingsGridCellSpacingLabelContent {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsGridCellSpacingLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide group header if only one group is available.
        /// </summary>
        internal static string EditSmartbarSettingsHideGroupHeaderIfOnlyOneAvailable {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsHideGroupHeaderIfOnlyOneAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string EditSmartbarSettingsLanguageLabelContent {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsLanguageLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable and show updates to installed plugins.
        /// </summary>
        internal static string EditSmartbarSettingsNotificationOnPluginUpdates {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsNotificationOnPluginUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable and show updates to Smartbar.
        /// </summary>
        internal static string EditSmartbarSettingsNotificationOnSmartbarUpdate {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsNotificationOnSmartbarUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string EditSmartbarSettingsNotificationsTabItemHeader {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsNotificationsTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhibit moving of Smartbar.
        /// </summary>
        internal static string EditSmartbarSettingsPinSmartbarAtPosition {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsPinSmartbarAtPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL key disables this behaviour while pressed..
        /// </summary>
        internal static string EditSmartbarSettingsPinSmartbarAtPositionTooltip {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsPinSmartbarAtPositionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string EditSmartbarSettingsPluginSettingsTabItemHeader {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsPluginSettingsTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the position of Smartbar on each start up.
        /// </summary>
        internal static string EditSmartbarSettingsRestorePosition {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsRestorePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows:.
        /// </summary>
        internal static string EditSmartbarSettingsRowsLabelContent {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsRowsLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statusbar (show the application name on hover).
        /// </summary>
        internal static string EditSmartbarSettingsShowStatusbar {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsShowStatusbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick to screen borders.
        /// </summary>
        internal static string EditSmartbarSettingsSnapOnScreenBorders {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsSnapOnScreenBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL + ALT keys disables this behaviour while pressed..
        /// </summary>
        internal static string EditSmartbarSettingsSnapOnScreenBordersTooltip {
            get {
                return ResourceManager.GetString("EditSmartbarSettingsSnapOnScreenBordersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no configurable plugins installed..
        /// </summary>
        internal static string NoConfigurablePluginsAvailableLabelContent {
            get {
                return ResourceManager.GetString("NoConfigurablePluginsAvailableLabelContent", resourceCulture);
            }
        }
    }
}
